using Microsoft.IdentityModel.Tokens;

namespace Masasamjant.AccessControl
{
    /// <summary>
    /// Defines supported JWT security algorithms.
    /// </summary>
    public enum JwtSecurityAlgorithm : int
    {
        None = 0,
        Aes128Encryption = 1,
        Aes192Encryption = 2,
        Aes256Encryption = 3,
        DesEncryption = 4,
        Aes128KeyWrap = 5,
        Aes192KeyWrap = 6,
        Aes256KeyWrap = 7,
        RsaV15KeyWrap = 8,
        Ripemd160Digest = 9,
        RsaOaepKeyWrap = 10,
        Aes128KW = 11,
        Aes192KW = 12,
        Aes256KW = 13,
        RsaPKCS1 = 14,
        RsaOAEP = 15,
        ExclusiveC14n = 16,
        ExclusiveC14nWithComments = 17,
        EnvelopedSignature = 18,
        Sha256Digest = 19,
        Sha384Digest = 20,
        Sha512Digest = 21,
        Sha256 = 22,
        Sha384 = 23,
        Sha512 = 24,
        EcdsaSha256Signature = 25,
        EcdsaSha384Signature = 26,
        EcdsaSha512Signature = 27,
        HmacSha256Signature = 28,
        HmacSha384Signature = 29,
        HmacSha512Signature = 30,
        RsaSha256Signature = 31,
        RsaSha384Signature = 32,
        RsaSha512Signature = 33,
        RsaSsaPssSha256Signature = 34,
        RsaSsaPssSha384Signature = 35,
        RsaSsaPssSha512Signature = 36,
        EcdsaSha256 = 37,
        EcdsaSha384 = 38,
        EcdsaSha512 = 39,
        HmacSha256 = 40,
        HmacSha384 = 41,
        HmacSha512 = 42,
        RsaSha256 = 43,
        RsaSha384 = 44,
        RsaSha512 = 45,
        RsaSsaPssSha256 = 46,
        RsaSsaPssSha384 = 47,
        RsaSsaPssSha512 = 48,
        Aes128CbcHmacSha256 = 49,
        Aes192CbcHmacSha384 = 50,
        Aes256CbcHmacSha512 = 51,
        Aes128Gcm = 52,
        Aes192Gcm = 53,
        Aes256Gcm = 54,
        EcdhEsA128kw = 55,
        EcdhEsA192kw = 56,
        EcdhEsA256kw = 57,
        EcdhEs = 58
    }

    internal static class JwtSecurityAlgorithmExtensions
    {
        public static string ToAlgorithmString(this JwtSecurityAlgorithm algorithm)
        {
            return algorithm switch
            {
                JwtSecurityAlgorithm.None => SecurityAlgorithms.None,
                JwtSecurityAlgorithm.Aes128Encryption => SecurityAlgorithms.Aes128Encryption,
                JwtSecurityAlgorithm.Aes192Encryption => SecurityAlgorithms.Aes192Encryption,
                JwtSecurityAlgorithm.Aes256Encryption => SecurityAlgorithms.Aes256Encryption,
                JwtSecurityAlgorithm.DesEncryption => SecurityAlgorithms.DesEncryption,
                JwtSecurityAlgorithm.Aes128KeyWrap => SecurityAlgorithms.Aes128KeyWrap,
                JwtSecurityAlgorithm.Aes192KeyWrap => SecurityAlgorithms.Aes192KeyWrap,
                JwtSecurityAlgorithm.Aes256KeyWrap => SecurityAlgorithms.Aes256KeyWrap,
                JwtSecurityAlgorithm.RsaV15KeyWrap => SecurityAlgorithms.RsaV15KeyWrap,
                JwtSecurityAlgorithm.Ripemd160Digest => SecurityAlgorithms.Ripemd160Digest,
                JwtSecurityAlgorithm.RsaOaepKeyWrap => SecurityAlgorithms.RsaOaepKeyWrap,
                JwtSecurityAlgorithm.Aes128KW => SecurityAlgorithms.Aes128KW,
                JwtSecurityAlgorithm.Aes192KW => SecurityAlgorithms.Aes192KW,
                JwtSecurityAlgorithm.Aes256KW => SecurityAlgorithms.Aes256KW,
                JwtSecurityAlgorithm.RsaPKCS1 => SecurityAlgorithms.RsaPKCS1,
                JwtSecurityAlgorithm.RsaOAEP => SecurityAlgorithms.RsaOAEP,
                JwtSecurityAlgorithm.ExclusiveC14n => SecurityAlgorithms.ExclusiveC14n,
                JwtSecurityAlgorithm.ExclusiveC14nWithComments => SecurityAlgorithms.ExclusiveC14nWithComments,
                JwtSecurityAlgorithm.EnvelopedSignature => SecurityAlgorithms.EnvelopedSignature,
                JwtSecurityAlgorithm.Sha256Digest => SecurityAlgorithms.Sha256Digest,
                JwtSecurityAlgorithm.Sha384Digest => SecurityAlgorithms.Sha384Digest,
                JwtSecurityAlgorithm.Sha512Digest => SecurityAlgorithms.Sha512Digest,
                JwtSecurityAlgorithm.Sha256 => SecurityAlgorithms.Sha256,
                JwtSecurityAlgorithm.Sha384 => SecurityAlgorithms.Sha384,
                JwtSecurityAlgorithm.Sha512 => SecurityAlgorithms.Sha512,
                JwtSecurityAlgorithm.EcdsaSha256Signature => SecurityAlgorithms.EcdsaSha256Signature,
                JwtSecurityAlgorithm.EcdsaSha384Signature => SecurityAlgorithms.EcdsaSha384Signature,
                JwtSecurityAlgorithm.EcdsaSha512Signature => SecurityAlgorithms.EcdsaSha512Signature,
                JwtSecurityAlgorithm.HmacSha256Signature => SecurityAlgorithms.HmacSha256Signature,
                JwtSecurityAlgorithm.HmacSha384Signature => SecurityAlgorithms.HmacSha384Signature,
                JwtSecurityAlgorithm.HmacSha512Signature => SecurityAlgorithms.HmacSha512Signature,
                JwtSecurityAlgorithm.RsaSha256Signature => SecurityAlgorithms.RsaSha256Signature,
                JwtSecurityAlgorithm.RsaSha384Signature => SecurityAlgorithms.RsaSha384Signature,
                JwtSecurityAlgorithm.RsaSha512Signature => SecurityAlgorithms.RsaSha512Signature,
                JwtSecurityAlgorithm.RsaSsaPssSha256Signature => SecurityAlgorithms.RsaSsaPssSha256Signature,
                JwtSecurityAlgorithm.RsaSsaPssSha384Signature => SecurityAlgorithms.RsaSsaPssSha384Signature,
                JwtSecurityAlgorithm.RsaSsaPssSha512Signature => SecurityAlgorithms.RsaSsaPssSha512Signature,
                JwtSecurityAlgorithm.EcdsaSha256 => SecurityAlgorithms.EcdsaSha256,
                JwtSecurityAlgorithm.EcdsaSha384 => SecurityAlgorithms.EcdsaSha384,
                JwtSecurityAlgorithm.EcdsaSha512 => SecurityAlgorithms.EcdsaSha512,
                JwtSecurityAlgorithm.HmacSha256 => SecurityAlgorithms.HmacSha256,
                JwtSecurityAlgorithm.HmacSha384 => SecurityAlgorithms.HmacSha384,
                JwtSecurityAlgorithm.HmacSha512 => SecurityAlgorithms.HmacSha512,
                JwtSecurityAlgorithm.RsaSha256 => SecurityAlgorithms.RsaSha256,
                JwtSecurityAlgorithm.RsaSha384 => SecurityAlgorithms.RsaSha384,
                JwtSecurityAlgorithm.RsaSha512 => SecurityAlgorithms.RsaSha512,
                JwtSecurityAlgorithm.RsaSsaPssSha256 => SecurityAlgorithms.RsaSsaPssSha256,
                JwtSecurityAlgorithm.RsaSsaPssSha384 => SecurityAlgorithms.RsaSsaPssSha384,
                JwtSecurityAlgorithm.RsaSsaPssSha512 => SecurityAlgorithms.RsaSsaPssSha512,
                JwtSecurityAlgorithm.Aes128CbcHmacSha256 => SecurityAlgorithms.Aes128CbcHmacSha256,
                JwtSecurityAlgorithm.Aes192CbcHmacSha384 => SecurityAlgorithms.Aes192CbcHmacSha384,
                JwtSecurityAlgorithm.Aes256CbcHmacSha512 => SecurityAlgorithms.Aes256CbcHmacSha512,
                JwtSecurityAlgorithm.Aes128Gcm => SecurityAlgorithms.Aes128Gcm,
                JwtSecurityAlgorithm.Aes192Gcm => SecurityAlgorithms.Aes192Gcm,
                JwtSecurityAlgorithm.Aes256Gcm => SecurityAlgorithms.Aes256Gcm,
                JwtSecurityAlgorithm.EcdhEsA128kw => SecurityAlgorithms.EcdhEsA128kw,
                JwtSecurityAlgorithm.EcdhEsA192kw => SecurityAlgorithms.EcdhEsA192kw,
                JwtSecurityAlgorithm.EcdhEsA256kw => SecurityAlgorithms.EcdhEsA256kw,
                JwtSecurityAlgorithm.EcdhEs => SecurityAlgorithms.EcdhEs,
                _ => throw new NotSupportedException($"Algorithm '{algorithm}' is not supported."),
            };
        }
    }
}
